"""CLI command handlers, grouped by concern."""

from __future__ import annotations

from .state import (
    _project,
    cmd_advance,
    cmd_gate,
    cmd_list_shelved,
    cmd_next,
    cmd_pointer,
    cmd_quiet_status,
    cmd_resume,
    cmd_shelf,
    cmd_shell,
    cmd_skip,
    cmd_status,
    cmd_sync,
    cmd_version,
)
from .team import (
    cmd_archive,
    cmd_claim,
    cmd_list_work,
    cmd_release,
    cmd_sync_team,
    cmd_team,
)
from .context import (
    cmd_accept,
    cmd_capture,
    cmd_complete,
    cmd_context,
    cmd_session,
    cmd_start,
)
from .integrations import (
    cmd_commit_message,
    cmd_issues,
    cmd_links,
    cmd_sunset,
    cmd_sync_links,
    cmd_sync_roadmap,
)
from .storage import (
    cmd_db,
    cmd_installer,
    cmd_local,
    cmd_quick,
    cmd_template,
    cmd_viewer,
    cmd_work,
)

__all__ = [
    "_project",
    "cmd_accept",
    "cmd_advance",
    "cmd_archive",
    "cmd_capture",
    "cmd_claim",
    "cmd_commit_message",
    "cmd_complete",
    "cmd_context",
    "cmd_db",
    "cmd_gate",
    "cmd_installer",
    "cmd_issues",
    "cmd_links",
    "cmd_list_shelved",
    "cmd_list_work",
    "cmd_local",
    "cmd_next",
    "cmd_pointer",
    "cmd_quick",
    "cmd_quiet_status",
    "cmd_release",
    "cmd_resume",
    "cmd_session",
    "cmd_shelf",
    "cmd_shell",
    "cmd_skip",
    "cmd_start",
    "cmd_status",
    "cmd_sunset",
    "cmd_sync",
    "cmd_sync_links",
    "cmd_sync_roadmap",
    "cmd_sync_team",
    "cmd_team",
    "cmd_template",
    "cmd_version",
    "cmd_viewer",
    "cmd_work",
]
