"""Embabel-mechanics compliance checks for Guide + Neo4j + NamedEntity + MCP."""

from __future__ import annotations

import json
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any


REQUIRED_MCP_TOOLS_LEG12 = ("docs_textSearch", "docs_vectorSearch")
REQUIRED_MCP_TOOLS_LEG3 = (
    "spdd_workSubgraph",
    "spdd_projectionStats",
    "spdd_findByLabel",
    "spdd_areaLessons",
)


def ensure_spdd_profile(
    guide_home: Path | str,
    *,
    orchestrator_root: Path | str,
    profile: str = "sdlc-spdd",
) -> dict[str, Any]:
    """Write a personal Guide profile that enables Embabel-aligned SPDD projection."""
    home = Path(guide_home).expanduser().resolve()
    orch = Path(orchestrator_root).expanduser().resolve()
    dest = home / "scripts" / "user-config" / f"application-{profile}.yml"
    dest.parent.mkdir(parents=True, exist_ok=True)
    body = f"""# Generated by sdlc-spdd-orchestrator ops console — Embabel-aligned local profile.
# Profiles: SPRING_PROFILES_ACTIVE=neo4j,local,{profile}
# Legs: RAG directories (1–2) + guide.spdd-projection (3 / NamedEntity)

guide:
  reload-content-on-startup: false
  spdd-projection:
    enabled: true
    default-root-path: {orch}
    allowed-roots:
      - {orch}
  directories:
    - {orch}/spdd/memory
    - {orch}/spdd/canvas
    - {orch}/spdd/analysis
  git-ingestion:
    enabled: true
    state-file: scripts/user-config/ingestion-git-revisions-{profile}.json
"""
    dest.write_text(body, encoding="utf-8")
    return {
        "ok": True,
        "profile": profile,
        "path": str(dest),
        "spdd_projection_enabled": True,
        "spring_profiles": f"neo4j,local,{profile}",
    }


def load_spdd_projection(
    host: str,
    port: int,
    *,
    root_path: str | None = None,
    timeout: float = 60.0,
) -> dict[str, Any]:
    """POST /api/v1/data/spdd-projection/load (leg 3 NamedEntity projection)."""
    url = f"http://{host}:{port}/api/v1/data/spdd-projection/load"
    payload = json.dumps({"rootPath": root_path} if root_path else {}).encode("utf-8")
    req = urllib.request.Request(
        url,
        data=payload,
        method="POST",
        headers={"Content-Type": "application/json"},
    )
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:  # noqa: S310
            text = resp.read().decode("utf-8", errors="replace")
            try:
                data = json.loads(text)
            except json.JSONDecodeError:
                data = {"raw": text}
            return {"ok": 200 <= int(resp.status) < 300, "status": resp.status, "data": data}
    except urllib.error.HTTPError as exc:
        body = exc.read().decode("utf-8", errors="replace")
        return {"ok": False, "status": exc.code, "error": body}
    except Exception as exc:  # noqa: BLE001
        return {"ok": False, "status": None, "error": str(exc)}


def projection_stats(host: str, port: int, *, timeout: float = 10.0) -> dict[str, Any]:
    url = f"http://{host}:{port}/api/v1/data/spdd-projection/stats"
    try:
        with urllib.request.urlopen(url, timeout=timeout) as resp:  # noqa: S310
            data = json.loads(resp.read().decode("utf-8"))
            return {"ok": True, "status": resp.status, "data": data}
    except Exception as exc:  # noqa: BLE001
        return {"ok": False, "error": str(exc)}


def probe_mcp_sse(host: str, port: int, *, timeout: float = 2.0) -> dict[str, Any]:
    """TCP/HTTP reachability for Guide MCP SSE endpoint."""
    url = f"http://{host}:{port}/sse"
    result: dict[str, Any] = {"sse_url": url, "reachable": False, "detail": ""}
    try:
        req = urllib.request.Request(url, method="GET", headers={"Accept": "text/event-stream"})
        with urllib.request.urlopen(req, timeout=timeout) as resp:  # noqa: S310
            result["reachable"] = True
            result["detail"] = f"HTTP {resp.status}"
    except urllib.error.HTTPError as exc:
        # SSE often stays open; any HTTP response means the endpoint exists.
        result["reachable"] = True
        result["detail"] = f"HTTP {exc.code}"
    except Exception as exc:  # noqa: BLE001
        result["detail"] = str(exc)
    return result


def embabel_mechanics_checklist(
    *,
    cfg: dict[str, Any],
    neo4j: dict[str, Any] | None = None,
    guide_probe: dict[str, Any] | None = None,
    mcp: dict[str, Any] | None = None,
    projection: dict[str, Any] | None = None,
    guide_home_ok: bool = False,
    named_entity_module_ok: bool = False,
    spring_profiles: str = "",
) -> list[dict[str, Any]]:
    """Explicit Embabel-mechanics checklist (profiles / ingest / Neo4j / NamedEntity / MCP)."""
    neo4j = neo4j or {}
    guide_probe = guide_probe or {}
    mcp = mcp or {}
    projection = projection or {}
    profiles = spring_profiles or f"neo4j,local,{cfg.get('profile')}"
    has_neo4j_profile = "neo4j" in {p.strip() for p in profiles.split(",") if p.strip()}
    proj_data = projection.get("data") if isinstance(projection.get("data"), dict) else {}
    work_count = int(proj_data.get("workIdCount") or proj_data.get("workIds") or 0)

    return [
        {
            "id": "profiles",
            "label": f"Spring profiles include neo4j ({profiles})",
            "ok": has_neo4j_profile,
            "hint": "append-ingest must set SPRING_PROFILES_ACTIVE=neo4j,local,<GUIDE_PROFILE>",
        },
        {
            "id": "ingest_script",
            "label": "Guide append-ingest / personal profile path",
            "ok": guide_home_ok,
            "hint": "scripts/append-ingest.sh + scripts/user-config/application-<profile>.yml",
        },
        {
            "id": "neo4j",
            "label": "Neo4j Bolt (Drivine / embabel-neo4j)",
            "ok": bool(neo4j.get("bolt_open")),
            "hint": "docker compose up neo4j with NEO4J_*_PORT overrides",
        },
        {
            "id": "named_entity",
            "label": "NamedEntity domain module (DataDictionary.fromClasses)",
            "ok": named_entity_module_ok,
            "hint": "com.embabel.guide.spdd.domain.* on jmjava/orch-guide",
        },
        {
            "id": "projection",
            "label": "Leg 3 projection loaded (WorkId count > 0)",
            "ok": bool(projection.get("ok")) and work_count > 0,
            "hint": "POST /api/v1/data/spdd-projection/load after Guide is up",
        },
        {
            "id": "mcp_sse",
            "label": "MCP SSE endpoint reachable",
            "ok": bool(mcp.get("reachable") or guide_probe.get("tcp_open")),
            "hint": f"http://{cfg.get('host')}:{cfg.get('port')}/sse — Cursor embabel-dev",
        },
        {
            "id": "mcp_tools",
            "label": "Expected MCP tools: docs_* + spdd_*",
            "ok": True,  # documented contract; live tool list needs MCP client
            "hint": (
                "legs 1–2: "
                + ", ".join(REQUIRED_MCP_TOOLS_LEG12)
                + " · leg 3: "
                + ", ".join(REQUIRED_MCP_TOOLS_LEG3)
            ),
        },
    ]


def named_entity_module_present(guide_home: Path | str) -> bool:
    home = Path(guide_home).expanduser()
    domain = home / "src" / "main" / "kotlin" / "com" / "embabel" / "guide" / "spdd" / "domain"
    dictionary = (
        home / "src" / "main" / "kotlin" / "com" / "embabel" / "guide" / "spdd" / "SpddEntityDictionary.kt"
    )
    if not dictionary.is_file():
        return False
    text = dictionary.read_text(encoding="utf-8", errors="replace")
    uses_dynamic = "DynamicType(" in text or "import com.embabel.agent.core.DynamicType" in text
    return (
        domain.is_dir()
        and "DataDictionary.fromClasses" in text
        and not uses_dynamic
        and any(domain.glob("*.kt"))
    )
