"""
Manim scenes for SDLC-SPDD Orchestrator docgen demo videos.

Pacing is driven by timing.json (generated by ``docgen timestamps``).
Scene classes are hand-maintained minimal title/diagram cards (CHORE-002).

Frame: 14.22 wide x 8 tall. Keep mobjects inside safe bounds (see helpers).
"""

from __future__ import annotations

import json
from pathlib import Path

from manim import *  # noqa: F401,F403

# ── Palette ──────────────────────────────────────────────────────────
C_BG = "#1e1e2e"
C_ACCENT = "#667eea"
C_GREEN = "#42b883"
C_ORANGE = "#f9a825"
C_BLUE = "#2979ff"
C_TEAL = "#26c6da"
C_WHITE = "#cdd6f4"

SAFE_CONTENT_WIDTH = 12.85
SAFE_BOTTOM_Y = -3.55


def _row_fit(*parts, buff=0.38):
    row = VGroup(*parts).arrange(RIGHT, buff=buff)
    if row.width > SAFE_CONTENT_WIDTH:
        row.scale(SAFE_CONTENT_WIDTH / row.width)
    return row


def _column_fit_below_title(title: Mobject, column: Mobject, buff=0.55):
    column.next_to(title, DOWN, buff=buff)
    required_top = title.get_bottom()[1] - buff
    actual_top = column.get_top()[1]
    if actual_top > required_top:
        column.shift(DOWN * (actual_top - required_top))
    bottom_y = column.get_bottom()[1]
    if bottom_y < SAFE_BOTTOM_Y:
        top_y = column.get_top()[1]
        available = max(top_y - SAFE_BOTTOM_Y, 0.25)
        if column.height > 1e-6 and available < column.height:
            column.scale(available / column.height, about_point=column.get_top())
    return column


def _load_timing(segment_key: str) -> list[dict]:
    timing_path = Path(__file__).parent / "timing.json"
    if not timing_path.exists():
        return []
    data = json.loads(timing_path.read_text())
    return data.get(segment_key, {}).get("segments", [])


def _load_timing_words(segment_key: str) -> list[dict]:
    timing_path = Path(__file__).parent / "timing.json"
    if not timing_path.exists():
        return []
    data = json.loads(timing_path.read_text())
    block = data.get(segment_key) or {}
    words = block.get("words")
    return list(words) if isinstance(words, list) else []


def _box(label, color, w=2.2, h=0.75, fs=18):
    r = RoundedRectangle(
        corner_radius=0.15,
        width=w,
        height=h,
        stroke_color=color,
        fill_color=color,
        fill_opacity=0.2,
    )
    t = Text(str(label), font_size=fs, color=color)
    inner_w = max(w - 0.25, 0.35)
    inner_h = max(h - 0.2, 0.35)
    if t.width > inner_w:
        t.scale(inner_w / t.width)
    if t.height > inner_h:
        t.scale(inner_h / t.height)
    t.move_to(r.get_center())
    return VGroup(r, t)


def _tail_wait(scene: "_TimedScene", timing_key: str, fallback: float = 14.0) -> None:
    words = _load_timing_words(timing_key)
    if words:
        scene.wait_until(max(float(w.get("end", 0.0)) for w in words))
        return
    segs = _load_timing(timing_key)
    if segs:
        scene.wait_until(max(float(s.get("end", 0.0)) for s in segs))
        return
    scene.timed_wait(fallback)


class _TimedScene(Scene):
    def setup(self):
        self._clock = 0.0

    def timed_play(self, *animations, run_time=1.0, **kwargs):
        self.play(*animations, run_time=run_time, **kwargs)
        self._clock += run_time

    def wait_until(self, target: float):
        gap = target - self._clock
        if gap > 0.05:
            self.wait(gap)
            self._clock += gap

    def timed_wait(self, duration: float):
        if duration > 0.05:
            self.wait(duration)
            self._clock += duration


class SdlcSpddIntroScene(_TimedScene):
    """Segment 01 - three-part framework + REASONS loop."""

    def construct(self):
        self.camera.background_color = C_BG
        key = "01-sdlc-spdd-intro"

        title = Text("SDLC-SPDD Orchestrator", font_size=34, color=C_ACCENT).to_edge(UP)
        self.timed_play(Write(title), run_time=1.2)

        planning = _box("Planning", C_BLUE, 2.8, 0.85, 20)
        spdd = _box("SPDD", C_GREEN, 2.8, 0.85, 20)
        agents = _box("SDLC Agents", C_TEAL, 2.8, 0.85, 20)
        parts = _row_fit(planning, spdd, agents, buff=0.35)
        _column_fit_below_title(title, parts)

        reasons = _box("REASONS Canvas", C_ORANGE, 5.5, 0.85, 22)
        reasons_labels = _row_fit(
            _box("R", C_WHITE, 0.9, 0.65, 16),
            _box("E", C_WHITE, 0.9, 0.65, 16),
            _box("A", C_WHITE, 0.9, 0.65, 16),
            _box("S", C_WHITE, 0.9, 0.65, 16),
            _box("O", C_WHITE, 0.9, 0.65, 16),
            _box("N", C_WHITE, 0.9, 0.65, 16),
            _box("S", C_WHITE, 0.9, 0.65, 16),
            buff=0.12,
        )
        stack = VGroup(parts, reasons, reasons_labels).arrange(DOWN, buff=0.45, center=True)
        _column_fit_below_title(title, stack)

        self.timed_play(FadeIn(planning), run_time=0.8)
        self.timed_play(FadeIn(spdd), run_time=0.8)
        self.timed_play(FadeIn(agents), run_time=0.8)
        self.timed_play(FadeIn(reasons), run_time=0.9)
        self.timed_play(FadeIn(reasons_labels), run_time=0.9)

        _tail_wait(self, key)
        self.timed_play(*[FadeOut(m) for m in self.mobjects], run_time=0.8)


class InstallWorkflowScene(_TimedScene):
    """Segment 02 - install into a target + workflow steps 1-6."""

    def construct(self):
        self.camera.background_color = C_BG
        key = "02-install-and-workflow"

        title = Text("Install & Daily Workflow", font_size=32, color=C_BLUE).to_edge(UP)
        self.timed_play(Write(title), run_time=1.0)

        steps = [
            _box("Clone orchestrator", C_ACCENT, 3.2, 0.8, 17),
            _box("setup-agent-prompts", C_GREEN, 3.2, 0.8, 17),
            _box("verify install", C_GREEN, 3.2, 0.8, 17),
            _box("Resume Prompt session", C_TEAL, 3.2, 0.8, 17),
            _box("analysis -> plan -> code", C_ORANGE, 3.2, 0.8, 17),
        ]
        column = VGroup(*steps).arrange(DOWN, buff=0.28, center=True)
        _column_fit_below_title(title, column)

        for step in steps:
            self.timed_play(FadeIn(step), run_time=0.75)

        _tail_wait(self, key)
        self.timed_play(*[FadeOut(m) for m in self.mobjects], run_time=0.8)


class GuideRagDogfoodScene(_TimedScene):
    """Segment 03 - Guide RAG research and dogfooding."""

    def construct(self):
        self.camera.background_color = C_BG
        key = "03-guide-rag-dogfood"

        title = Text("Guide RAG & Dogfooding", font_size=32, color=C_TEAL).to_edge(UP)
        self.timed_play(Write(title), run_time=1.0)

        profiles = _row_fit(
            _box("menke", C_GREEN, 1.8, 0.75, 16),
            _box("menke-2", C_GREEN, 1.8, 0.75, 16),
            _box("menke-3", C_BLUE, 1.8, 0.75, 16),
            _box("menke-4", C_BLUE, 1.8, 0.75, 16),
            buff=0.2,
        )
        mcp = _box("MCP vector + text search", C_ACCENT, 5.0, 0.85, 18)
        dogfood = _box("SPDD + docgen + Guide on self", C_ORANGE, 5.0, 0.85, 18)
        stack = VGroup(profiles, mcp, dogfood).arrange(DOWN, buff=0.4, center=True)
        _column_fit_below_title(title, stack)

        self.timed_play(FadeIn(profiles), run_time=0.9)
        self.timed_play(FadeIn(mcp), run_time=0.85)
        self.timed_play(FadeIn(dogfood), run_time=0.85)

        _tail_wait(self, key)
        self.timed_play(*[FadeOut(m) for m in self.mobjects], run_time=0.8)
