#!/usr/bin/env bash
# Thin wrapper: the roadmap summary is generated by the Python engine
# (sdlc-engine sync-roadmap). Kept so existing prompts and docs keep working.
set -euo pipefail

_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=/dev/null
source "${_SCRIPT_DIR}/lib/common.sh"
# shellcheck source=/dev/null
source "${_SCRIPT_DIR}/lib/python.sh"

usage() {
  cat <<'EOF'
Usage: sync-roadmap-from-spdd.sh [--target <path>] [--roadmap <file>] [--dry-run]

Update the managed SDLC-SPDD summary section in sdlc-spdd/ROADMAP.md from
sdlc-spdd/spdd/canvas/*.md. Content outside these markers is preserved:
  <!-- SDLC-SPDD-ROADMAP-SUMMARY:START -->
  <!-- SDLC-SPDD-ROADMAP-SUMMARY:END -->

--roadmap is relative to the sdlc-spdd/ home unless absolute.
EOF
}

TARGET="."
ROADMAP="ROADMAP.md"
DRY_RUN=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --target)
      TARGET="${2:-}"
      shift 2
      ;;
    --roadmap)
      ROADMAP="${2:-}"
      shift 2
      ;;
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

TARGET="$(sdlc_resolve_target "${TARGET}")"

engine_args=(sync-roadmap --roadmap "${ROADMAP}")
[[ "${DRY_RUN}" -eq 1 ]] && engine_args+=(--dry-run)
sdlc_engine_run "${TARGET}" "${engine_args[@]}"

if [[ "${DRY_RUN}" -eq 0 ]]; then
  echo
  echo "Planning review prompt (see sdlc-spdd/docs/planning-prompt-standard.md):"
  echo "  Read @sdlc-spdd/ROADMAP.md. Review the SDLC-SPDD Work Summary table. Does Current Focus match the active Work ID and phase?"
fi
