"""
Manim scenes for docgen demo videos.

Pacing is driven by timing.json (generated by ``docgen timestamps``).
Scene classes below this header are injected by ``docgen scene-spec-generate``
/ ``docgen scene-compile`` between marker blocks; helpers and palette are
hand-maintained.

Frame: 14.22 wide x 8 tall.  Coordinates x in [-7.11, 7.11], y in [-4, 4].
Keep **all** mobjects inside this rectangle: wide `arrange(RIGHT)` rows and long
`next_to(..., DOWN)` chains both clip in 720p unless bounded (see `_row_fit`,
`_column_fit_below_title`).
"""

from __future__ import annotations

import json
from pathlib import Path

from manim import *  # noqa: F401,F403

# ── Palette ──────────────────────────────────────────────────────────
C_BG = "#1e1e2e"
C_ACCENT = "#667eea"
C_GREEN = "#42b883"
C_ORANGE = "#f9a825"
C_BLUE = "#2979ff"
C_RED = "#ff5252"
C_TEAL = "#26c6da"
C_PURPLE = "#ce93d8"
C_WHITE = "#cdd6f4"

# Layout: default Manim 16:9 frame ~14.22 x 8. Leave margin so nothing touches edges.
SAFE_CONTENT_WIDTH = 12.85
SAFE_BOTTOM_Y = -3.55


def _row_fit(*parts, buff=0.38):
    """Single horizontal row scaled to fit ``SAFE_CONTENT_WIDTH`` (prevents off-screen RIGHT)."""
    row = VGroup(*parts).arrange(RIGHT, buff=buff)
    if row.width > SAFE_CONTENT_WIDTH:
        row.scale(SAFE_CONTENT_WIDTH / row.width)
    return row


def _column_fit_below_title(title: Mobject, column: Mobject, buff=0.55):
    """Stack / column placed under ``title``; uniform scale if bottom would fall below ``SAFE_BOTTOM_Y``.

    Also enforces a hard non-overlap with the title's bounding box: after
    ``next_to``, if the column's top would still be above ``title.bottom - buff``
    (e.g. because the caller scaled the title via an ``.animate`` chain that
    Manim resolves with a different bbox than expected), the column is shifted
    DOWN by the missing clearance. This makes title-overlap impossible regardless
    of how the title was last transformed.
    """
    column.next_to(title, DOWN, buff=buff)
    required_top = title.get_bottom()[1] - buff
    actual_top = column.get_top()[1]
    if actual_top > required_top:
        column.shift(DOWN * (actual_top - required_top))
    bottom_y = column.get_bottom()[1]
    if bottom_y < SAFE_BOTTOM_Y:
        top_y = column.get_top()[1]
        available = max(top_y - SAFE_BOTTOM_Y, 0.25)
        if column.height > 1e-6 and available < column.height:
            column.scale(available / column.height, about_point=column.get_top())
    return column


def _load_timing(segment_key: str) -> list[dict]:
    """Return Whisper segments from timing.json for a given segment key."""
    timing_path = Path(__file__).parent / "timing.json"
    if not timing_path.exists():
        return []
    data = json.loads(timing_path.read_text())
    return data.get(segment_key, {}).get("segments", [])


def _load_timing_words(segment_key: str) -> list[dict]:
    """Return Whisper word-level entries from timing.json (``words`` list)."""
    timing_path = Path(__file__).parent / "timing.json"
    if not timing_path.exists():
        return []
    data = json.loads(timing_path.read_text())
    block = data.get(segment_key) or {}
    words = block.get("words")
    return list(words) if isinstance(words, list) else []


def _box(label, color, w=2.2, h=0.75, fs=18, subtitle=""):
    """Labeled rounded box - slightly stronger fill/stroke for readable diagram boards.

    Optional ``subtitle`` is a second, smaller line under the primary label
    (decorative; not used for wait_word beat matching).
    """
    r = RoundedRectangle(
        corner_radius=0.18, width=w, height=h,
        stroke_color=color, stroke_width=2.5,
        fill_color=color, fill_opacity=0.28,
    )
    t = Text(str(label), font_size=fs, color=C_WHITE)
    # Prefer white label text for contrast; fall back to the accent color when
    # the palette token is already near-white.
    if str(color) in (C_WHITE, "C_WHITE", "#cdd6f4"):
        t.set_color(color)
    sub = str(subtitle or "").strip()
    if sub:
        sub_fs = max(10, int(fs * 0.72))
        s = Text(sub, font_size=sub_fs, color=C_WHITE)
        if str(color) in (C_WHITE, "C_WHITE", "#cdd6f4"):
            s.set_color(color)
        s.set_opacity(0.85)
        text = VGroup(t, s).arrange(DOWN, buff=0.06)
    else:
        text = t
    inner_w = max(w - 0.3, 0.35)
    inner_h = max(h - 0.22, 0.35)
    if text.width > inner_w:
        text.scale(inner_w / text.width)
    if text.height > inner_h:
        text.scale(inner_h / text.height)
    text.move_to(r.get_center())
    return VGroup(r, text)


def _arrow(start, end, color="#cdd6f4", style="solid"):
    """Connector between box centers (used by scene-spec ``edges``).

    ``style`` is ``solid`` (default) or ``dashed``. Dashed edges should be
    revealed with ``FadeIn`` (not ``GrowArrow``).
    """
    # Allow palette token names that compile_scene_class emits as bare identifiers.
    arr = Arrow(
        start,
        end,
        color=color,
        stroke_width=3,
        buff=0.2,
        max_tip_length_to_length_ratio=0.15,
    )
    if str(style).strip().lower() == "dashed":
        return DashedVMobject(arr, num_dashes=18, dashed_ratio=0.55)
    return arr


def _image(relpath, w=3.0, h=2.0):
    """ImageMobject for a bundle-relative asset, scaled to fit inside w x h.

    ``relpath`` is relative to the bundle directory (parent of animations/),
    e.g. ``images/architecture.png``. Assets are produced by
    ``docgen image-generate`` from scene-spec prompts. Fails loud when the
    file is missing so a scene never renders with a silent gap.
    """
    p = Path(__file__).resolve().parent.parent / relpath
    if not p.is_file():
        raise FileNotFoundError(
            f"scene image asset missing: {p} - run `docgen image-generate` "
            "(or add the file) before `docgen manim`."
        )
    img = ImageMobject(str(p))
    scale = min(w / max(img.width, 1e-6), h / max(img.height, 1e-6))
    img.scale(scale)
    return img


class _TimedScene(Scene):
    """Base with a clock that tracks elapsed scene time."""

    def setup(self):
        self._clock = 0.0

    def timed_play(self, *animations, run_time=1.0, **kwargs):
        self.play(*animations, run_time=run_time, **kwargs)
        self._clock += run_time

    def wait_until(self, target: float):
        gap = target - self._clock
        if gap > 0.05:
            self.wait(gap)
            self._clock += gap

    def timed_wait(self, duration: float):
        if duration > 0.05:
            self.wait(duration)
            self._clock += duration

    def wait_until_word(self, words, index: int):
        """Wait until Whisper ``words[index]['start']`` (no-op if index invalid)."""
        if not words or index < 0 or index >= len(words):
            return
        try:
            t = float(words[index].get("start", 0.0))
        except (TypeError, ValueError):
            return
        self.wait_until(t)

    def pace_to_beat(self, segments, beat_index, num_beats, segment_indices=None):
        """Wait until the Whisper segment start for this story beat.

        If ``segment_indices`` is a sequence of Whisper **segment** indices (one per beat),
        use ``segment_indices[beat_index]`` as the segment row index. Otherwise spread
        beats evenly across segment indices (legacy behaviour).
        """
        if not segments or num_beats <= 0:
            return
        n = len(segments)
        if segment_indices is not None:
            if beat_index < 0 or beat_index >= num_beats:
                return
            if beat_index >= len(segment_indices):
                return
            j = int(segment_indices[beat_index])
            j = max(0, min(n - 1, j))
            self.wait_until(float(segments[j].get("start", 0.0)))
            return
        if n == 1:
            self.wait_until(float(segments[0].get("start", 0.0)))
            return
        si = min(int(round(beat_index * (n - 1) / max(num_beats - 1, 1))), n - 1)
        self.wait_until(float(segments[si].get("start", 0.0)))

    def paced_reveal(self, segments, mobjects, segment_indices, run_time=0.55):
        """Reveal each mobject at its paired Whisper segment start.

        For each ``mobjects[k]`` paired with ``segment_indices[k]``: wait until that
        Whisper segment's ``start`` (via ``pace_to_beat``) and play ``FadeIn(mobject)``
        with the mobject already laid out at its final position. Caller MUST NOT
        pre-set opacity to 0 on the mobjects -- ``FadeIn`` animates 0 -> the
        mobject's current opacity, so an invisible target stays invisible.

        If there are more ``mobjects`` than ``segment_indices`` the extras are spread
        evenly across the remaining Whisper segments. If ``segments`` is empty the
        mobjects fade in immediately, in order, with no pacing.
        """
        if not mobjects:
            return
        n_m = len(mobjects)
        indices = list(segment_indices) if segment_indices is not None else []
        if not segments:
            for m in mobjects:
                self.timed_play(FadeIn(m), run_time=run_time)
            return
        for k, m in enumerate(mobjects):
            if k < len(indices):
                self.pace_to_beat(segments, k, len(indices), indices)
            else:
                self.pace_to_beat(segments, k, n_m)
            self.timed_play(FadeIn(m), run_time=run_time)

# ── BEGIN GENERATED SCENE: 01 (SdlcSpddIntroScene) ──
class SdlcSpddIntroScene(_TimedScene):
    def construct(self):
        self.camera.background_color = C_BG
        timing_words = _load_timing_words('01-sdlc-spdd-intro')

        title = Text('SDLC-SPDD Orchestrator', font_size=34, color=C_ACCENT).to_edge(UP)
        self.timed_play(Write(title), run_time=1.0)

        _bx_0_0_0 = _box('AI-assisted coding', C_RED, 5.2, 0.85, 20)
        _bx_0_0_1 = _box('context lives in chat', C_BLUE, 5.2, 0.85, 20)
        _bx_0_1_0 = _box('next agent', C_ORANGE, 5.2, 0.85, 20)
        _bx_0_1_1 = _box('partial conversation', C_ORANGE, 5.2, 0.85, 20)
        _bx_0_2_0 = _box('SDLC-SPDD Orchestrator', C_GREEN, 6.5, 0.9, 22)
        _row_0_0 = VGroup(_bx_0_0_0, _bx_0_0_1).arrange(RIGHT, buff=0.3)
        _row_0_1 = VGroup(_bx_0_1_0, _bx_0_1_1).arrange(RIGHT, buff=0.3)
        _row_0_2 = VGroup(_bx_0_2_0)
        _p0_stack = VGroup(_row_0_0, _row_0_1, _row_0_2).arrange(DOWN, buff=0.35, center=True)
        _p0_stack.next_to(title, DOWN, buff=0.45)
        _bx_1_0_0 = _box('version-controlled files', C_TEAL, 6.0, 0.85, 20)
        _bx_1_0_1 = _box('deliberately hybrid', C_ACCENT, 5.0, 0.85, 20)
        _bx_1_1_0 = _box('Planning', C_BLUE, 3.5, 0.85, 20)
        _bx_1_1_1 = _box('SPDD', C_GREEN, 3.5, 0.85, 20)
        _bx_1_1_2 = _box('SDLC Agents', C_TEAL, 3.5, 0.85, 20)
        _bx_1_2_0 = _box('REASONS Canvas', C_ORANGE, 6.5, 0.9, 22)
        _row_1_0 = VGroup(_bx_1_0_0, _bx_1_0_1).arrange(RIGHT, buff=0.3)
        _row_1_1 = VGroup(_bx_1_1_0, _bx_1_1_1, _bx_1_1_2).arrange(RIGHT, buff=0.3)
        _row_1_2 = VGroup(_bx_1_2_0)
        _p1_stack = VGroup(_row_1_0, _row_1_1, _row_1_2).arrange(DOWN, buff=0.35, center=True)
        _p1_stack.next_to(title, DOWN, buff=0.45)
        _bx_2_0_0 = _box('Requirements', C_WHITE, 3.5, 0.75, 18)
        _bx_2_0_1 = _box('Entities', C_WHITE, 3.5, 0.75, 18)
        _bx_2_0_2 = _box('Approach', C_WHITE, 3.5, 0.75, 18)
        _bx_2_1_0 = _box('Structure', C_WHITE, 3.5, 0.75, 18)
        _bx_2_1_1 = _box('Operations', C_WHITE, 3.5, 0.75, 18)
        _bx_2_1_2 = _box('Norms and Safeguards', C_WHITE, 4.2, 0.75, 16)
        _bx_2_2_0 = _box('align on that artifact', C_ORANGE, 6.5, 0.8, 18)
        _row_2_0 = VGroup(_bx_2_0_0, _bx_2_0_1, _bx_2_0_2).arrange(RIGHT, buff=0.3)
        _row_2_1 = VGroup(_bx_2_1_0, _bx_2_1_1, _bx_2_1_2).arrange(RIGHT, buff=0.3)
        _row_2_2 = VGroup(_bx_2_2_0)
        _p2_stack = VGroup(_row_2_0, _row_2_1, _row_2_2).arrange(DOWN, buff=0.35, center=True)
        _p2_stack.next_to(title, DOWN, buff=0.45)
        _bx_3_0_0 = _box('ops console', C_BLUE, 5.2, 0.85, 20)
        _bx_3_0_1 = _box('ADF Viewer', C_GREEN, 5.2, 0.85, 20)
        _bx_3_1_0 = _box('following steps', C_TEAL, 5.2, 0.85, 20)
        _bx_3_1_1 = _box('target project', C_ACCENT, 5.2, 0.85, 20)
        _row_3_0 = VGroup(_bx_3_0_0, _bx_3_0_1).arrange(RIGHT, buff=0.3)
        _row_3_1 = VGroup(_bx_3_1_0, _bx_3_1_1).arrange(RIGHT, buff=0.3)
        _p3_stack = VGroup(_row_3_0, _row_3_1).arrange(DOWN, buff=0.35, center=True)
        _p3_stack.next_to(title, DOWN, buff=0.45)

        self.wait_until_word(timing_words, 1)
        self.timed_play(FadeIn(_bx_0_0_0), run_time=1.2)
        self.wait_until_word(timing_words, 10)
        self.timed_play(FadeIn(_bx_0_0_1), run_time=1.2)
        self.wait_until_word(timing_words, 23)
        self.timed_play(FadeIn(_bx_0_1_0), run_time=1.2)
        self.wait_until_word(timing_words, 30)
        self.timed_play(FadeIn(_bx_0_1_1), run_time=1.2)
        self.wait_until_word(timing_words, 32)
        self.timed_play(FadeIn(_bx_0_2_0), run_time=1.2)
        self.wait_until_word(timing_words, 54)
        self.timed_play(FadeOut(_bx_0_0_0), FadeOut(_bx_0_0_1), FadeOut(_bx_0_1_0), FadeOut(_bx_0_1_1), FadeOut(_bx_0_2_0), run_time=0.45)
        self.timed_play(FadeIn(_bx_1_0_0), run_time=1.2)
        self.wait_until_word(timing_words, 75)
        self.timed_play(FadeIn(_bx_1_0_1), run_time=1.2)
        self.wait_until_word(timing_words, 77)
        self.timed_play(FadeIn(_bx_1_1_0), run_time=1.2)
        self.wait_until_word(timing_words, 91)
        self.timed_play(FadeIn(_bx_1_1_1), run_time=1.2)
        self.wait_until_word(timing_words, 109)
        self.timed_play(FadeIn(_bx_1_1_2), run_time=1.2)
        self.wait_until_word(timing_words, 121)
        self.timed_play(FadeIn(_bx_1_2_0), run_time=1.2)
        self.wait_until_word(timing_words, 130)
        self.timed_play(FadeOut(_bx_1_0_0), FadeOut(_bx_1_0_1), FadeOut(_bx_1_1_0), FadeOut(_bx_1_1_1), FadeOut(_bx_1_1_2), FadeOut(_bx_1_2_0), run_time=0.45)
        self.timed_play(FadeIn(_bx_2_0_0), run_time=1.0)
        self.wait_until_word(timing_words, 138)
        self.timed_play(FadeIn(_bx_2_0_1), run_time=1.0)
        self.wait_until_word(timing_words, 145)
        self.timed_play(FadeIn(_bx_2_0_2), run_time=1.0)
        self.wait_until_word(timing_words, 149)
        self.timed_play(FadeIn(_bx_2_1_0), run_time=1.0)
        self.wait_until_word(timing_words, 155)
        self.timed_play(FadeIn(_bx_2_1_1), run_time=1.0)
        self.wait_until_word(timing_words, 162)
        self.timed_play(FadeIn(_bx_2_1_2), run_time=1.0)
        self.wait_until_word(timing_words, 171)
        self.timed_play(FadeIn(_bx_2_2_0), run_time=1.0)
        self.wait_until_word(timing_words, 183)
        self.timed_play(FadeOut(_bx_2_0_0), FadeOut(_bx_2_0_1), FadeOut(_bx_2_0_2), FadeOut(_bx_2_1_0), FadeOut(_bx_2_1_1), FadeOut(_bx_2_1_2), FadeOut(_bx_2_2_0), run_time=0.45)
        self.timed_play(FadeIn(_bx_3_0_0), run_time=0.49)
        self.wait_until_word(timing_words, 186)
        self.timed_play(FadeIn(_bx_3_0_1), run_time=1.2)
        self.wait_until_word(timing_words, 204)
        self.timed_play(FadeIn(_bx_3_1_0), run_time=1.2)
        self.wait_until_word(timing_words, 216)
        self.timed_play(FadeIn(_bx_3_1_1), run_time=1.2)

        # docgen: audio-length tail (waits through full TTS; run after `docgen timestamps`)
        if timing_words:
            self.wait_until(
                max(float(w.get("end", 0.0)) for w in timing_words)
            )
        else:
            _docgen_segs = _load_timing('01-sdlc-spdd-intro')
            if _docgen_segs:
                self.wait_until(
                    max(float(s.get("end", 0.0)) for s in _docgen_segs)
                )
        self.timed_play(*[FadeOut(m) for m in self.mobjects], run_time=1.0)
        self.timed_wait(0.5)
# ── END GENERATED SCENE: 01 ──

# ── BEGIN GENERATED SCENE: 02 (InstallWorkflowScene) ──
class InstallWorkflowScene(_TimedScene):
    def construct(self):
        self.camera.background_color = C_BG
        timing_words = _load_timing_words('02-install-and-workflow')

        title = Text('Install & Workflow', font_size=32, color=C_BLUE).to_edge(UP)
        self.timed_play(Write(title), run_time=1.0)

        _bx_0_0_0 = _box('orchestrator repository', C_ACCENT, 6.5, 0.85, 20)
        _bx_0_1_0 = _box('setup-agent-prompts.sh', C_GREEN, 5.2, 0.85, 18)
        _bx_0_1_1 = _box('verify-project-install.sh', C_GREEN, 5.2, 0.85, 18)
        _bx_0_2_0 = _box('three-part scaffold', C_TEAL, 4.0, 0.85, 18)
        _bx_0_2_1 = _box('Cursor', C_BLUE, 2.2, 0.85, 18)
        _bx_0_2_2 = _box('GitHub Copilot', C_BLUE, 3.2, 0.85, 16)
        _bx_0_2_3 = _box('Claude Code', C_BLUE, 2.8, 0.85, 16)
        _row_0_0 = VGroup(_bx_0_0_0)
        _row_0_1 = VGroup(_bx_0_1_0, _bx_0_1_1).arrange(RIGHT, buff=0.28)
        _row_0_2 = VGroup(_bx_0_2_0, _bx_0_2_1, _bx_0_2_2, _bx_0_2_3).arrange(RIGHT, buff=0.28)
        _p0_stack = VGroup(_row_0_0, _row_0_1, _row_0_2).arrange(DOWN, buff=0.32, center=True)
        _p0_stack.next_to(title, DOWN, buff=0.45)
        _bx_1_0_0 = _box('ops console', C_TEAL, 5.0, 0.85, 20)
        _bx_1_0_1 = _box('port 5051', C_TEAL, 4.0, 0.85, 20)
        _bx_1_1_0 = _box('dogfood installs', C_GREEN, 4.0, 0.85, 18)
        _bx_1_1_1 = _box('SQLite management', C_GREEN, 4.0, 0.85, 18)
        _bx_1_1_2 = _box('Guide lifecycle', C_GREEN, 3.8, 0.85, 18)
        _bx_1_2_0 = _box('ADF Viewer', C_PURPLE, 5.0, 0.85, 20)
        _bx_1_2_1 = _box('port 5050', C_PURPLE, 4.0, 0.85, 20)
        _row_1_0 = VGroup(_bx_1_0_0, _bx_1_0_1).arrange(RIGHT, buff=0.28)
        _row_1_1 = VGroup(_bx_1_1_0, _bx_1_1_1, _bx_1_1_2).arrange(RIGHT, buff=0.28)
        _row_1_2 = VGroup(_bx_1_2_0, _bx_1_2_1).arrange(RIGHT, buff=0.28)
        _p1_stack = VGroup(_row_1_0, _row_1_1, _row_1_2).arrange(DOWN, buff=0.32, center=True)
        _p1_stack.next_to(title, DOWN, buff=0.45)
        _bx_2_0_0 = _box('Shell scripts', C_ORANGE, 6.5, 0.85, 20)
        _bx_2_1_0 = _box('first session', C_BLUE, 5.0, 0.85, 20)
        _bx_2_1_1 = _box('workflow table', C_GREEN, 5.0, 0.85, 20)
        _bx_2_2_0 = _box('setting up prompts', C_ACCENT, 5.0, 0.85, 20)
        _bx_2_2_1 = _box('sdlc-spdd-init', C_ACCENT, 5.0, 0.85, 20)
        _bx_2_3_0 = _box('Work IDs', C_BLUE, 4.5, 0.85, 20)
        _bx_2_3_1 = _box('Ready For Coding', C_TEAL, 5.5, 0.85, 20)
        _row_2_0 = VGroup(_bx_2_0_0)
        _row_2_1 = VGroup(_bx_2_1_0, _bx_2_1_1).arrange(RIGHT, buff=0.28)
        _row_2_2 = VGroup(_bx_2_2_0, _bx_2_2_1).arrange(RIGHT, buff=0.28)
        _row_2_3 = VGroup(_bx_2_3_0, _bx_2_3_1).arrange(RIGHT, buff=0.28)
        _p2_stack = VGroup(_row_2_0, _row_2_1, _row_2_2, _row_2_3).arrange(DOWN, buff=0.32, center=True)
        _p2_stack.next_to(title, DOWN, buff=0.45)

        self.wait_until_word(timing_words, 6)
        self.timed_play(FadeIn(_bx_0_0_0), run_time=1.1)
        self.wait_until_word(timing_words, 9)
        self.timed_play(FadeIn(_bx_0_1_0), run_time=1.1)
        self.wait_until_word(timing_words, 22)
        self.timed_play(FadeIn(_bx_0_1_1), run_time=1.1)
        self.wait_until_word(timing_words, 29)
        self.timed_play(FadeIn(_bx_0_2_0), run_time=1.1)
        self.wait_until_word(timing_words, 39)
        self.timed_play(FadeIn(_bx_0_2_1), run_time=0.72)
        self.wait_until_word(timing_words, 40)
        self.timed_play(FadeIn(_bx_0_2_2), run_time=1.1)
        self.wait_until_word(timing_words, 44)
        self.timed_play(FadeIn(_bx_0_2_3), run_time=1.1)
        self.wait_until_word(timing_words, 48)
        self.timed_play(FadeOut(_bx_0_0_0), FadeOut(_bx_0_1_0), FadeOut(_bx_0_1_1), FadeOut(_bx_0_2_0), FadeOut(_bx_0_2_1), FadeOut(_bx_0_2_2), FadeOut(_bx_0_2_3), run_time=0.45)
        self.timed_play(FadeIn(_bx_1_0_0), run_time=1.1)
        self.wait_until_word(timing_words, 57)
        self.timed_play(FadeIn(_bx_1_0_1), run_time=1.1)
        self.wait_until_word(timing_words, 63)
        self.timed_play(FadeIn(_bx_1_1_0), run_time=1.1)
        self.wait_until_word(timing_words, 65)
        self.timed_play(FadeIn(_bx_1_1_1), run_time=1.1)
        self.wait_until_word(timing_words, 69)
        self.timed_play(FadeIn(_bx_1_1_2), run_time=1.1)
        self.wait_until_word(timing_words, 72)
        self.timed_play(FadeIn(_bx_1_2_0), run_time=1.1)
        self.wait_until_word(timing_words, 76)
        self.timed_play(FadeIn(_bx_1_2_1), run_time=1.1)
        self.wait_until_word(timing_words, 89)
        self.timed_play(FadeOut(_bx_1_0_0), FadeOut(_bx_1_0_1), FadeOut(_bx_1_1_0), FadeOut(_bx_1_1_1), FadeOut(_bx_1_1_2), FadeOut(_bx_1_2_0), FadeOut(_bx_1_2_1), run_time=0.45)
        self.timed_play(FadeIn(_bx_2_0_0), run_time=1.1)
        self.wait_until_word(timing_words, 98)
        self.timed_play(FadeIn(_bx_2_1_0), run_time=1.1)
        self.wait_until_word(timing_words, 143)
        self.timed_play(FadeIn(_bx_2_1_1), run_time=1.1)
        self.wait_until_word(timing_words, 156)
        self.timed_play(FadeIn(_bx_2_2_0), run_time=1.1)
        self.wait_until_word(timing_words, 165)
        self.timed_play(FadeIn(_bx_2_2_1), run_time=1.1)
        self.wait_until_word(timing_words, 213)
        self.timed_play(FadeIn(_bx_2_3_0), run_time=1.1)
        self.wait_until_word(timing_words, 231)
        self.timed_play(FadeIn(_bx_2_3_1), run_time=1.1)

        # docgen: audio-length tail (waits through full TTS; run after `docgen timestamps`)
        if timing_words:
            self.wait_until(
                max(float(w.get("end", 0.0)) for w in timing_words)
            )
        else:
            _docgen_segs = _load_timing('02-install-and-workflow')
            if _docgen_segs:
                self.wait_until(
                    max(float(s.get("end", 0.0)) for s in _docgen_segs)
                )
        self.timed_play(*[FadeOut(m) for m in self.mobjects], run_time=1.0)
        self.timed_wait(0.5)
# ── END GENERATED SCENE: 02 ──

# ── BEGIN GENERATED SCENE: 03 (GuideRagDogfoodScene) ──
class GuideRagDogfoodScene(_TimedScene):
    def construct(self):
        self.camera.background_color = C_BG
        timing_words = _load_timing_words('03-guide-rag-dogfood')

        title = Text('Guide RAG & Dogfooding', font_size=32, color=C_TEAL).to_edge(UP)
        self.timed_play(Write(title), run_time=1.0)

        _bx_0_0_0 = _box('publish a framework', C_ACCENT, 5.5, 0.85, 20)
        _bx_0_0_1 = _box('intentional dogfooding', C_ORANGE, 5.5, 0.85, 20)
        _bx_0_1_0 = _box('Embabel Guide', C_GREEN, 4.2, 0.85, 20)
        _bx_0_1_1 = _box('Neo4j', C_BLUE, 3.0, 0.85, 20)
        _bx_0_1_2 = _box('optional local backend', C_TEAL, 4.5, 0.85, 18)
        _bx_0_2_0 = _box('Markdown files', C_WHITE, 4.0, 0.85, 20)
        _bx_0_2_1 = _box('file indexes', C_ACCENT, 4.0, 0.85, 20)
        _bx_0_2_2 = _box('not an error', C_GREEN, 3.5, 0.85, 18)
        _row_0_0 = VGroup(_bx_0_0_0, _bx_0_0_1).arrange(RIGHT, buff=0.28)
        _row_0_1 = VGroup(_bx_0_1_0, _bx_0_1_1, _bx_0_1_2).arrange(RIGHT, buff=0.28)
        _row_0_2 = VGroup(_bx_0_2_0, _bx_0_2_1, _bx_0_2_2).arrange(RIGHT, buff=0.28)
        _p0_stack = VGroup(_row_0_0, _row_0_1, _row_0_2).arrange(DOWN, buff=0.32, center=True)
        _p0_stack.next_to(title, DOWN, buff=0.45)
        _bx_1_0_0 = _box('provisional go', C_TEAL, 5.0, 0.85, 20)
        _bx_1_0_1 = _box('sdlc-spdd-projection-v1', C_ACCENT, 5.5, 0.85, 18)
        _bx_1_1_0 = _box('ops console', C_BLUE, 4.5, 0.85, 20)
        _bx_1_1_1 = _box('Guide tab', C_BLUE, 4.5, 0.85, 20)
        _bx_1_2_0 = _box('RAG chunks', C_ORANGE, 4.5, 0.85, 20)
        _bx_1_2_1 = _box('typed domain entities', C_GREEN, 5.5, 0.85, 18)
        _row_1_0 = VGroup(_bx_1_0_0, _bx_1_0_1).arrange(RIGHT, buff=0.28)
        _row_1_1 = VGroup(_bx_1_1_0, _bx_1_1_1).arrange(RIGHT, buff=0.28)
        _row_1_2 = VGroup(_bx_1_2_0, _bx_1_2_1).arrange(RIGHT, buff=0.28)
        _p1_stack = VGroup(_row_1_0, _row_1_1, _row_1_2).arrange(DOWN, buff=0.32, center=True)
        _p1_stack.next_to(title, DOWN, buff=0.45)
        _bx_2_0_0 = _box('MCP tools', C_BLUE, 4.5, 0.85, 20)
        _bx_2_0_1 = _box('posture guard', C_PURPLE, 4.5, 0.85, 20)
        _bx_2_1_0 = _box('ADF Viewer', C_ORANGE, 4.5, 0.85, 20)
        _bx_2_1_1 = _box('does not talk', C_TEAL, 4.5, 0.85, 20)
        _row_2_0 = VGroup(_bx_2_0_0, _bx_2_0_1).arrange(RIGHT, buff=0.28)
        _row_2_1 = VGroup(_bx_2_1_0, _bx_2_1_1).arrange(RIGHT, buff=0.28)
        _p2_stack = VGroup(_row_2_0, _row_2_1).arrange(DOWN, buff=0.32, center=True)
        _p2_stack.next_to(title, DOWN, buff=0.45)
        _bx_3_0_0 = _box('research infrastructure', C_WHITE, 5.5, 0.85, 18)
        _bx_3_0_1 = _box('target projects', C_GREEN, 4.5, 0.85, 18)
        _bx_3_1_0 = _box('guide-dice', C_ACCENT, 5.5, 0.85, 20)
        _row_3_0 = VGroup(_bx_3_0_0, _bx_3_0_1).arrange(RIGHT, buff=0.28)
        _row_3_1 = VGroup(_bx_3_1_0)
        _p3_stack = VGroup(_row_3_0, _row_3_1).arrange(DOWN, buff=0.32, center=True)
        _p3_stack.next_to(title, DOWN, buff=0.45)

        self.wait_until_word(timing_words, 5)
        self.timed_play(FadeIn(_bx_0_0_0), run_time=1.1)
        self.wait_until_word(timing_words, 30)
        self.timed_play(FadeIn(_bx_0_0_1), run_time=1.1)
        self.wait_until_word(timing_words, 46)
        self.timed_play(FadeIn(_bx_0_1_0), run_time=1.1)
        self.wait_until_word(timing_words, 49)
        self.timed_play(FadeIn(_bx_0_1_1), run_time=0.692)
        self.wait_until_word(timing_words, 52)
        self.timed_play(FadeIn(_bx_0_1_2), run_time=1.1)
        self.wait_until_word(timing_words, 55)
        self.timed_play(FadeIn(_bx_0_2_0), run_time=1.1)
        self.wait_until_word(timing_words, 72)
        self.timed_play(FadeIn(_bx_0_2_1), run_time=1.1)
        self.wait_until_word(timing_words, 77)
        self.timed_play(FadeIn(_bx_0_2_2), run_time=1.1)
        self.wait_until_word(timing_words, 86)
        self.timed_play(FadeOut(_bx_0_0_0), FadeOut(_bx_0_0_1), FadeOut(_bx_0_1_0), FadeOut(_bx_0_1_1), FadeOut(_bx_0_1_2), FadeOut(_bx_0_2_0), FadeOut(_bx_0_2_1), FadeOut(_bx_0_2_2), run_time=0.45)
        self.timed_play(FadeIn(_bx_1_0_0), run_time=1.1)
        self.wait_until_word(timing_words, 99)
        self.timed_play(FadeIn(_bx_1_0_1), run_time=1.1)
        self.wait_until_word(timing_words, 103)
        self.timed_play(FadeIn(_bx_1_1_0), run_time=0.758)
        self.wait_until_word(timing_words, 105)
        self.timed_play(FadeIn(_bx_1_1_1), run_time=1.1)
        self.wait_until_word(timing_words, 131)
        self.timed_play(FadeIn(_bx_1_2_0), run_time=1.1)
        self.wait_until_word(timing_words, 137)
        self.timed_play(FadeIn(_bx_1_2_1), run_time=1.1)
        self.wait_until_word(timing_words, 154)
        self.timed_play(FadeOut(_bx_1_0_0), FadeOut(_bx_1_0_1), FadeOut(_bx_1_1_0), FadeOut(_bx_1_1_1), FadeOut(_bx_1_2_0), FadeOut(_bx_1_2_1), run_time=0.45)
        self.timed_play(FadeIn(_bx_2_0_0), run_time=1.1)
        self.wait_until_word(timing_words, 237)
        self.timed_play(FadeIn(_bx_2_0_1), run_time=1.1)
        self.wait_until_word(timing_words, 248)
        self.timed_play(FadeIn(_bx_2_1_0), run_time=1.1)
        self.wait_until_word(timing_words, 263)
        self.timed_play(FadeIn(_bx_2_1_1), run_time=1.1)
        self.wait_until_word(timing_words, 271)
        self.timed_play(FadeOut(_bx_2_0_0), FadeOut(_bx_2_0_1), FadeOut(_bx_2_1_0), FadeOut(_bx_2_1_1), run_time=0.45)
        self.timed_play(FadeIn(_bx_3_0_0), run_time=1.1)
        self.wait_until_word(timing_words, 275)
        self.timed_play(FadeIn(_bx_3_0_1), run_time=1.1)
        self.wait_until_word(timing_words, 302)
        self.timed_play(FadeIn(_bx_3_1_0), run_time=1.1)

        # docgen: audio-length tail (waits through full TTS; run after `docgen timestamps`)
        if timing_words:
            self.wait_until(
                max(float(w.get("end", 0.0)) for w in timing_words)
            )
        else:
            _docgen_segs = _load_timing('03-guide-rag-dogfood')
            if _docgen_segs:
                self.wait_until(
                    max(float(s.get("end", 0.0)) for s in _docgen_segs)
                )
        self.timed_play(*[FadeOut(m) for m in self.mobjects], run_time=1.0)
        self.timed_wait(0.5)
# ── END GENERATED SCENE: 03 ──
